### ISSUE TITLE
Confirm/ensure support of Terraform 0.15

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#425]
[Terraform 0.15.0-beta1 was released recently](https://github.com/hashicorp/terraform/issues/27917) and we need to check whether it is fully compatible with the language server.

### TODO

 - [x] Reflect any CLI changes (should already be reflected in the latest `terraform-exec`, but https://github.com/hashicorp/terraform-exec/issues/13 may need to be looked at)
 - [x] https://github.com/hashicorp/terraform-exec/issues/141 - https://github.com/hashicorp/terraform-json/pull/29
 - [x] Reflect schema changes https://github.com/hashicorp/terraform-schema/issues/21
    - [x] `NestedType` introduced in https://github.com/hashicorp/terraform/pull/27699 and https://github.com/hashicorp/terraform/pull/27793
       - [x] https://github.com/hashicorp/terraform/pull/28055
       - [x] https://github.com/hashicorp/terraform-json/issues/27 / https://github.com/hashicorp/terraform-json/pull/28
       - [x] https://github.com/hashicorp/terraform-schema/pull/31
    - [x] `provider_requirements` changes introduced in https://github.com/hashicorp/terraform/pull/27739
       - [x] https://github.com/hashicorp/hcl-lang/pull/23
       - [x] https://github.com/hashicorp/terraform-schema/pull/24
       - [x] https://github.com/hashicorp/terraform-schema/pull/26
    - [x] `terraform` `language` https://github.com/hashicorp/terraform/pull/27941 - https://github.com/hashicorp/terraform-schema/pull/29
 - [x] Reflect any changes in how Terraform installs and stores modules and plugins in `.terraform` directory
