### ISSUE TITLE
Recognize individual expressions when nested

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-ls#496]
## Background (current state)

Through the logic in [`hcl-lang/schema`](https://pkg.go.dev/github.com/hashicorp/hcl-lang@v0.0.0-20210506073550-8dbfc108aa73/schema) and related schema in [`terraform-schema`](https://pkg.go.dev/github.com/hashicorp/terraform-schema) we currently provide completion, hover and semantic highlighting for the _outermost expression_ (with a few exceptions for HCL objects and tuples) and generally don't take into account (potentially infinite) nesting.

### Completion

```hcl
resource "aws_instance" "example" {
  ami = # HERE
  depends_on = [ HERE ]
}
```
For `ami` we can provide completion of any `string` candidates, for completion within `depends_on` brackets we can provide references to other resources and data sources.

### Hover

```hcl
resource "aws_instance" "example" {
  ami = "test"
  depends_on = [ aws_vpc.test ]
}
```
When hovering over `"test"` we can match the string constant against schema (string type) and show relevant popup (`"test"` _string_). Similarly when hovering over `[ aws_vpc.test ]` we can match it against schema (set of references) and show relevant popup (_set of references_).

### Semantic Tokens

```hcl
resource "aws_instance" "example" {
  ami = "test"
  depends_on = [ aws_vpc.test ]
}
```
Here `"test"` is expected to be string (per schema) and `aws_vpc.test` is expected to be a reference (per schema), so LS will report relevant semantic tokens in both cases.

## Use-cases

User would benefit from recognition of arbitrarily nested expressions in all relevant functions of the LS, as described in more detail below.

### Completion

```hcl
resource "aws_instance" "example" {
  ami = "ami-${HERE}"
  depends_on = [
    aws_vpc.test,
    # HERE
  ]
}
```

within `${}` we should provide any compatible expressions (presumably all primitive types).
for the second position we should provide any available references other than `aws_vpc.test`.

### Hover

```hcl
resource "aws_instance" "example" {
  ami = "ami-${data.aws_ami.example.test.image_id}"
  depends_on = [
    aws_vpc.test,
  ]
}
```
when hovering over `data.aws_ami.example.test.id` we display popup with details about the reference (_string_ `The ID of the AMI.`)
when hover over `aws_vpc.test` we display popup with details about the reference (_resource_).

### Semantic Tokens

```hcl
resource "aws_instance" "example" {
  ami = "ami-${data.aws_ami.example.test.image_id}"
  cpu_core_count = 2 * var.core_count
}
```

`"ami-${data.aws_ami.example.test.image_id}"` is highlighted as a template expression with `ami-` highlighted as string and `data.aws_ami.example.test.image_id` as reference.

`2 * var.core_count` is highlighted as multiplication expression with `2` highlighted as number and `var.core_count` as a reference.

## Proposal

 - [ ] Add (failing) tests to cover existing nested expressions
   - [x] completion
     - [x] inside `hclsyntax.TupleConsExpr` (`attr = [ var.foo, _ ]`)
     - [x] inside `hclsyntax.ObjectConsItem` (`attr = { foo = _ }`) in the context of object/map as value & `object({})` type declaration
     - [x] inside `hclsyntax.ObjectConsExpr` (`attr = { _ }`) in the context of object/map as value & `object({})` type declaration
     - [ ] inside `hclsyntax.TemplateExpr` (`attr = "${_}"`)
     - [x] inside `hclsyntax.FunctionCallExpr` (`attr = fun(_)`) in the context of type declarations such as `list()`, `set()`, `map()` & [built-in functions](https://github.com/hashicorp/terraform-ls/issues/37)
   - [x] hover
     - [x] inside `hclsyntax.TupleConsExpr` (`attr = [ var.foo, _ ]`)
     - [x] inside `hclsyntax.ObjectConsItem` (`attr = { foo = _ }`) in the context of object/map as value & `object({})` type declaration
     - [x] inside `hclsyntax.ObjectConsExpr` (`attr = { _ }`) in the context of object/map as value & `object({})` type declaration
     - [ ] inside `hclsyntax.TemplateExpr` (`attr = "${_}"`)
     - [x] inside `hclsyntax.FunctionCallExpr` (`attr = fun(_)`) in the context of type declarations such as `list()`, `set()`, `map()` & [built-in functions](https://github.com/hashicorp/terraform-ls/issues/37)
   - [x] semantic tokens
     - [x] inside `hclsyntax.TupleConsExpr` (`attr = [ var.foo, _ ]`)
     - [x] inside `hclsyntax.ObjectConsItem` (`attr = { foo = _ }`) in the context of object/map as value & `object({})` type declaration
     - [x] inside `hclsyntax.ObjectConsExpr` (`attr = { _ }`) in the context of object/map as value & `object({})` type declaration
     - [ ] inside `hclsyntax.TemplateExpr` (`attr = "${_}"`)
     - [x] inside `hclsyntax.FunctionCallExpr` (`attr = fun(_)`) in the context of type declarations such as `list()`, `set()`, `map()` & [built-in functions](https://github.com/hashicorp/terraform-ls/issues/37)
 - `hashicorp/hcl-lang`
   - [x] Deprecate [`schema.TupleConsExpr`](https://pkg.go.dev/github.com/hashicorp/hcl-lang@v0.0.0-20220411091131-f24c834260e0/schema#TupleConsExpr)
   - [x] Create `Expression interface` in `decoder` such that completion for any expression type can be delegated and each type can also delegate completion of nested expressions to other expression types
   - [x] Implement `decoder.NewExpression(expr hcl.Expression, cons schema.ExprConstraints) Expression`
   - [x] Implement `schema.ObjectTypeDeclItemExpr`
   - [x] Implement new completion candidate kinds?
      - [x] `lang.PrimitiveTypeDeclExpr`
      - [x] `lang.ComplexTypeDeclExpr`
      - [x] `lang.ObjectTypeDeclItemExpr`
   - [x] Implement `schema.AnyExprOfType{Type: cty.Type}` to act as an alias to
      - `schema.LiteralTypeExpr`
      - `schema.TraversalExpr`
      - (future) dynamically express function calls which return the `Type`
      - (future) dynamically express templates which return the `Type`
      - (future) dynamically express conditional expressions which return the `Type`
      - (future) dynamically express operator expressions which return the `Type`
   - [x] Implement `LiteralValueExpr` as `decoder.Expression`
   - [x] Implement `ScopeTraversalExpr` as `decoder.Expression` (for type declarations, references and keywords)
   - [x] Implement `TupleConsExpr` as `decoder.Expression`
   - [x] Implement `ObjectConsExpr` as `decoder.Expression`
   - [x] Implement (basic) `FunctionCallExpr` as `decoder.Expression` (for type declarations)
   - [ ] Implement (basic) `TemplateExpr` as `decoder.Expression`
   - [ ] Implement (basic) `TemplateWrapExpr` as `decoder.Expression`
   - [x] Plumb all new `decoder.Expression` types into `PathDecoder` - `CandidatesAtPos`
   - [x] Plumb all new `decoder.Expression` types into `PathDecoder` - `HoverAtPos`
   - [x] Plumb all new `decoder.Expression` types into `PathDecoder` - `SemanticTokensInFile`

```go
type Expression interface {
	CandidatesAtPos(ctx context.Context, pos hcl.Pos) []lang.Candidate
	HoverAtPos(ctx context.Context, pos hcl.Pos) *lang.HoverData
	SemanticTokens(ctx context.Context) []lang.SemanticToken
	// TODO: Validate()
}
```

Prototype WIP: https://github.com/hashicorp/hcl-lang/commit/d21a86326111de083c8adea196252d7bc55d42c5
